# Generated by Django 4.0.5 on 2022-07-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tutorial_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='featured_image',
            field=models.ImageField(default='featured_images/featured.jpg', upload_to='featured_images/'),
        ),
    ]
