# Generated by Django 4.0.5 on 2022-07-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_path_description_alter_topic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='path_id',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
