# Generated by Django 4.0.5 on 2022-07-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_path_path_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='path_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
