version: 2.1

jobs:
    hello-setup:
        docker:
            - image: python:3.10.0-alpine
        steps:
            - checkout
            - run:
                name: "Hello"
                command: |
                    echo "Hello from Bravin"
    
    my-dependancies:
        docker:
            - image: python:3.10.0-alpine
        steps:
            - checkout
            - attach_workspace:
                at: ~/
            - run:
                name: Dependancies
                command: |
                    python -m pip install --upgrade pip
                    pip install --trusted-host pypi.python.org --no-cache-dir -r requirements.txt
    
    my-tests:
        docker:
            - image: python:3.10.0-alpine
        steps:
            - checkout
            - attach_workspace:
                at: ~/
            - run:
                name: app tests
                command: |
                    echo "TODO: write django tests"

workflows:
  django-flow:
    jobs:
      - hello-setup
      - my-dependancies:
          requires: [hello-setup]
      - my-tests:
          requires: [my-dependancies]

    